### PR TITLE
Add dark theme

### PR DESCRIPTION
**Pull request by TechSupport26**
Create an option for other color themes.
#134

### CODE REVIEW

**Comment by TechSupport26** [comment]
So far I have made the buttons and their state is stored locally (I hope).

I believe creating a new variables.scss file that has a different color pallet and changing the file used when changing color preferences (perhaps in a similar way that the web/src/types/profile.ts is used) is all that is left to do.

**Comment by Connoropolous** [comment]
@TechSupport26 
great! We can pick up on this from here, and developing the styling for the dark mode. Do you want to fully hand this off to us?

**Comment by TechSupport26** [comment]
If that is easier for you then yes. I don't know how to implement a way of switching the colors in a clean way however I am happy to do what I can if needed.
Thanks.

**Comment by Connoropolous** [comment]
Yeah we are happy to take it on. It's really excellent that you're contributing. We're very happy to see it and support it.

**Comment by TechSupport26** [comment]
I just removed 2 files that I did not push and now Acorn does not compile. I will recreate them and push it so that it works. Whoops.

**Comment by kbonnici** [comment]
Amazing, thanks @TechSupport26. When i pulled your branch yesterday i had to comment out the lines in `reducer.ts` importing that theme file that seemingly didnt exist. Pulled your changes and now it works. Thanks!

**Comment by TechSupport26** [comment]
You are welcome.

By the way... There are 2 files that I made changes to that I did not need to so reverting them back should not cause anything to break.
`web/src/components/Button/Button.scss`
`web/src/event-listeners/index.ts`
And removing an "o" in `web/src/components/Preferences/Preferences.scss` line 71 (Not that it changed anything.)

I can push this but I don't want to butt in if I can help it.

**Pull request closed without merging**
